### ISSUE TITLE
SQL DB ERROR - incorrect integer value

### ISSUE THREAD

**Issue by violent01** [sader1992/sader_scripts#3]
File: sader's Reward Manager 1.3c
Version: 1.3c
configuration in the script:
modifications: nothing modified
How to Reproduce: insert a reward then claim it then go to your map server and you will see the picture below. Using rathena latest version.

![sader](https://user-images.githubusercontent.com/30449376/75270804-388f7900-580c-11ea-9638-0b76be3666a1.jpg)

**Comment by sader1992** [comment]
https://github.com/sader1992/sader_scripts/commit/f998d2696a5a47221f3d669a167389b160721553
thanks , this should fix it , however i will need to create a new version soon to be up to date with the last rathena features (also the script right now is a little messy)

**Comment by violent01** [comment]
Found another bug again using it. Sorry Sader for reporting this to you, I hope its not annoying.
File: sader's Reward Manager 1.3c
Version: 1.3c
configuration in the script:
modifications: nothing modified
How to Reproduce: click the npc and then select 'Check and Remove a reward' afterwards check your map server and it says the following below.

![sader](https://user-images.githubusercontent.com/30449376/75553377-5564c000-5a49-11ea-9f57-28c0e8a84c41.jpg)
