### ISSUE TITLE
sader_s_enchant_V3.0 error with random options

### ISSUE THREAD

**Issue by NoharaSuzuki** [sader1992/sader_scripts#4]
File:sader_s_enchant_V3.0.txt
Version:the last one?!
configuration in the script:default
modifications:default
How to Reproduce:have a item with 5(has to be 5)random options, with you use the enchant the npc take the last random options so you have the enchant(1 or more) and only 4 random options

**Comment by sader1992** [comment]
https://github.com/sader1992/sader_scripts/blob/master/rAthena/etc/sader_s_enchant/sader_s_enchant.txt
if you have the script already configered , change line 102
from
`	for(.@i=0;.@i<(MAX_ITEM_RDM_OPT-1);.@i++){`
to
`	for(.@i=0;.@i<(MAX_ITEM_RDM_OPT);.@i++){`
